# 2016  US Presidential Election
BA. 7차과제

### Import Data & Expore

In [1]:
import pandas as pd
from pandas import DataFrame as df
import numpy as np

fpath = "/Users/seolab/Downloads/2016-us-election/"
data = pd.read_csv(fpath+"county_facts.csv")
print(data.shape)
data.head()

(3195, 54)

,fips,area_name,state_abbreviation,PST045214,PST040210,PST120214,POP010210,AGE135214,AGE295214,AGE775214,...,SBO415207,SBO015207,MAN450207,WTN220207,RTN130207,RTN131207,AFN120207,BPS030214,LND110210,POP060210
0,0,United States,NaN,318857056,308758105,3.3,308745538,6.2,23.1,14.5,...,8.3,28.8,5319456312,4174286516,3917663456,12990,613795732,1046363,3531905.43,87.4
1,1000,Alabama,NaN,4849377,4780127,1.4,4779736,6.1,22.8,15.3,...,1.2,28.1,112858843,52252752,57344851,12364,6426342,13369,50645.33,94.4
2,1001,Autauga County,AL,55395,54571,1.5,54571,6.0,25.2,13.8,...,0.7,31.7,0,0,598175,12003,88157,131,594.44,91.8
3,1003,Baldwin County,AL,200111,182265,9.8,182265,5.6,22.2,18.7,...,1.3,27.3,1410273,0,2966489,17166,436955,1384,1589.78,114.6
4,1005,Barbour County,AL,26887,27457,-2.1,27457,5.7,21.2,16.5,...,0.0,27.0,0,0,188337,6334,0,8,884.88,31.0

In [2]:
cols = data.columns.values
cols

array(['fips', 'area_name', 'state_abbreviation', 'PST045214', 'PST040210',
       'PST120214', 'POP010210', 'AGE135214', 'AGE295214', 'AGE775214',
       'SEX255214', 'RHI125214', 'RHI225214', 'RHI325214', 'RHI425214',
       'RHI525214', 'RHI625214', 'RHI725214', 'RHI825214', 'POP715213',
       'POP645213', 'POP815213', 'EDU635213', 'EDU685213', 'VET605213',
       'LFE305213', 'HSG010214', 'HSG445213', 'HSG096213', 'HSG495213',
       'HSD410213', 'HSD310213', 'INC910213', 'INC110213', 'PVY020213',
       'BZA010213', 'BZA110213', 'BZA115213', 'NES010213', 'SBO001207',
       'SBO315207', 'SBO115207', 'SBO215207', 'SBO515207', 'SBO415207',
       'SBO015207', 'MAN450207', 'WTN220207', 'RTN130207', 'RTN131207',
       'AFN120207', 'BPS030214', 'LND110210', 'POP060210'], dtype=object)

In [3]:
print(len(set(data[cols[2]])))
print(len(data[data[cols[2]].isnull()==True]))
data[data[cols[2]].isnull()==True].head(10)

52
52

,fips,area_name,state_abbreviation,PST045214,PST040210,PST120214,POP010210,AGE135214,AGE295214,AGE775214,...,SBO415207,SBO015207,MAN450207,WTN220207,RTN130207,RTN131207,AFN120207,BPS030214,LND110210,POP060210
0,0,United States,NaN,318857056,308758105,3.3,308745538,6.2,23.1,14.5,...,8.3,28.8,5319456312,4174286516,3917663456,12990,613795732,1046363,3531905.43,87.4
1,1000,Alabama,NaN,4849377,4780127,1.4,4779736,6.1,22.8,15.3,...,1.2,28.1,112858843,52252752,57344851,12364,6426342,13369,50645.33,94.4
69,2000,Alaska,NaN,736732,710249,3.7,710231,7.4,25.3,9.4,...,0.0,25.9,8204030,4563605,9303387,13635,1851293,1518,570640.95,1.2
99,4000,Arizona,NaN,6731484,6392310,5.3,6392017,6.4,24.1,15.9,...,10.7,28.1,57977827,57573459,86758801,13637,13268514,26997,113594.08,56.3
115,5000,Arkansas,NaN,2966369,2915958,1.7,2915918,6.5,23.8,15.7,...,2.3,24.5,60735582,29659789,32974282,11602,3559795,7666,52035.48,56.0
191,6000,California,NaN,38802500,37254503,4.2,37253956,6.5,23.6,12.9,...,16.5,30.3,491372092,598456486,455032270,12561,80852787,83645,155779.22,239.1
250,8000,Colorado,NaN,5355866,5029324,6.5,5029196,6.3,23.3,12.7,...,6.2,29.2,46331953,53598986,65896788,13609,11440395,28686,103641.89,48.5
315,9000,Connecticut,NaN,3596677,3574096,0.6,3574097,5.3,21.6,15.5,...,4.2,28.1,58404898,107917037,52165480,14953,9138437,5329,4842.36,738.1
324,10000,Delaware,NaN,935614,897936,4.2,897934,6.0,21.8,16.4,...,2.1,26.1,25679939,5727401,14202083,16421,1910770,5194,1948.54,460.8
328,11000,District Of Columbia,NaN,658893,601767,9.5,601723,6.5,17.5,11.3,...,6.1,34.5,332844,2117990,3843716,6555,4278171,4189,61.05,9856.5

테이블의 구조를 가늠해볼 수 있다.
미국의 주(state)는 52개로 구성되어 있기때문에 `state_abbreviation`은 52개의 유니크한 값을 갖고, state에 속하는 `area_name` record를 갖는다.
이때 `state_abbreviation`가 null인 변수는 state에 대한 총합? 일 것으로 추정.
제일 첫번째 레코드는 미국 전체의 결과일 것으로 추정된다.

가볍게 state level에서 데이터를 탐색해보고 싶기때문에 세부적인 위 결과에서 미국 전체의 결과를 제외한 데이터셋을 사용하도록 하자.

In [4]:
fips_state = data[data[cols[2]].isnull()==True][cols[0]][1:]
abbr_state = {}
for f in fips_state:
    k = data[data[cols[0]]==f][cols[1]].values[0]
    if len(data[data[cols[0]]==f+1][cols[2]]) > 0:
        v = data[data[cols[0]]==f+1][cols[2]].values[0]
    else :
        continue
    abbr_state[k] = v
#abbr_state

In [5]:
data_raw = data.copy()
data = data[data[cols[2]].isnull()==True][1:]

In [6]:
data.head()

,fips,area_name,state_abbreviation,PST045214,PST040210,PST120214,POP010210,AGE135214,AGE295214,AGE775214,...,SBO415207,SBO015207,MAN450207,WTN220207,RTN130207,RTN131207,AFN120207,BPS030214,LND110210,POP060210
1,1000,Alabama,NaN,4849377,4780127,1.4,4779736,6.1,22.8,15.3,...,1.2,28.1,112858843,52252752,57344851,12364,6426342,13369,50645.33,94.4
69,2000,Alaska,NaN,736732,710249,3.7,710231,7.4,25.3,9.4,...,0.0,25.9,8204030,4563605,9303387,13635,1851293,1518,570640.95,1.2
99,4000,Arizona,NaN,6731484,6392310,5.3,6392017,6.4,24.1,15.9,...,10.7,28.1,57977827,57573459,86758801,13637,13268514,26997,113594.08,56.3
115,5000,Arkansas,NaN,2966369,2915958,1.7,2915918,6.5,23.8,15.7,...,2.3,24.5,60735582,29659789,32974282,11602,3559795,7666,52035.48,56.0
191,6000,California,NaN,38802500,37254503,4.2,37253956,6.5,23.6,12.9,...,16.5,30.3,491372092,598456486,455032270,12561,80852787,83645,155779.22,239.1

### variable descriptions

In [7]:
df_desc = pd.read_csv(fpath+"county_facts_dictionary.csv")
print(df_desc.shape)
df_desc.head()

(51, 2)

  column_name                                        description
0   PST045214                          Population, 2014 estimate
1   PST040210          Population, 2010 (April 1) estimates base
2   PST120214  Population, percent change - April 1, 2010 to ...
3   POP010210                                   Population, 2010
4   AGE135214               Persons under 5 years, percent, 2014

### import result dataset

In [9]:
df_res = pd.read_csv(fpath+"primary_results.csv")
df_res

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes
0,Alabama,AL,Autauga,1001.0,Democrat,Bernie Sanders,544,0.182
1,Alabama,AL,Autauga,1001.0,Democrat,Hillary Clinton,2387,0.800
2,Alabama,AL,Baldwin,1003.0,Democrat,Bernie Sanders,2694,0.329
3,Alabama,AL,Baldwin,1003.0,Democrat,Hillary Clinton,5290,0.647
4,Alabama,AL,Barbour,1005.0,Democrat,Bernie Sanders,222,0.078
5,Alabama,AL,Barbour,1005.0,Democrat,Hillary Clinton,2567,0.906
6,Alabama,AL,Bibb,1007.0,Democrat,Bernie Sanders,246,0.197
7,Alabama,AL,Bibb,1007.0,Democrat,Hillary Clinton,942,0.755
8,Alabama,AL,Blount,1009.0,Democrat,Bernie Sanders,395,0.386
9,Alabama,AL,Blount,1009.0,Democrat,Hillary Clinton,564,0.551
10,Alabama,AL,Bullock,1011.0,Democrat,Bernie Sanders,178,0.066
11,Alabama,AL,Bullock,1011.0,Democrat,Hillary Clinton,2451,0.913
12,Alabama,AL,Butler,1013.0,Democrat,Bernie Sanders,156,0.065
13,Alabama,AL,Butler,1013.0,Democrat,Hillary Clinton,2196,0.921
14,Alabama,AL,Calhoun,1015.0,Democrat,Bernie Sanders,1425,0.218
15,Alabama,AL,Calhoun,1015.0,Democrat,Hillary Clinton,5011,0.765
16,Alabama,AL,Chambers,1017.0,Democrat,Bernie Sanders,312,0.095
17,Alabama,AL,Chambers,1017.0,Democrat,Hillary Clinton,2899,0.886
18,Alabama,AL,Cherokee,1019.0,Democrat,Bernie Sanders,268,0.249
19,Alabama,AL,Cherokee,1019.0,Democrat,Hillary Clinton,712,0.661
20,Alabama,AL,Chilton,1021.0,Democrat,Bernie Sanders,289,0.246
21,Alabama,AL,Chilton,1021.0,Democrat,Hillary Clinton,860,0.731
22,Alabama,AL,Choctaw,1023.0,Democrat,Bernie Sanders,273,0.124
23,Alabama,AL,Choctaw,1023.0,Democrat,Hillary Clinton,1772,0.802
24,Alabama,AL,Clarke,1025.0,Democrat,Bernie Sanders,213,0.063
25,Alabama,AL,Clarke,1025.0,Democrat,Hillary Clinton,3148,0.930
26,Alabama,AL,Clay,1027.0,Democrat,Bernie Sanders,135,0.137
27,Alabama,AL,Clay,1027.0,Democrat,Hillary Clinton,807,0.818
28,Alabama,AL,Cleburne,1029.0,Democrat,Bernie Sanders,72,0.238
29,Alabama,AL,Cleburne,1029.0,Democrat,Hillary Clinton,221,0.732
...,...,...,...,...,...,...,...,...
24581,Wyoming,WY,Fremont-Park,95600029.0,Republican,Marco Rubio,0,0.000
24582,Wyoming,WY,Fremont-Park,95600029.0,Republican,Ted Cruz,64,0.660
24583,Wyoming,WY,Goshen-Platte,95600035.0,Republican,Donald Trump,0,0.000
24584,Wyoming,WY,Goshen-Platte,95600035.0,Republican,John Kasich,0,0.000
24585,Wyoming,WY,Goshen-Platte,95600035.0,Republican,Marco Rubio,0,0.000
24586,Wyoming,WY,Goshen-Platte,95600035.0,Republican,Ted Cruz,83,1.000
24587,Wyoming,WY,Hot Springs-Washakie,95600030.0,Republican,Donald Trump,0,0.000
24588,Wyoming,WY,Hot Springs-Washakie,95600030.0,Republican,John Kasich,0,0.000
24589,Wyoming,WY,Hot Springs-Washakie,95600030.0,Republican,Marco Rubio,0,0.000
24590,Wyoming,WY,Hot Springs-Washakie,95600030.0,Republican,Ted Cruz,43,1.000
24591,Wyoming,WY,Laramie,95600036.0,Republican,Donald Trump,0,0.000
24592,Wyoming,WY,Laramie,95600036.0,Republican,John Kasich,0,0.000
24593,Wyoming,WY,Laramie,95600036.0,Republican,Marco Rubio,38,0.176
24594,Wyoming,WY,Laramie,95600036.0,Republican,Ted Cruz,141,0.653
24595,Wyoming,WY,Sheridan-Big Horn,95600031.0,Republican,Donald Trump,0,0.000
24596,Wyoming,WY,Sheridan-Big Horn,95600031.0,Republican,John Kasich,0,0.000
24597,Wyoming,WY,Sheridan-Big Horn,95600031.0,Republican,Marco Rubio,30,0.400
24598,Wyoming,WY,Sheridan-Big Horn,95600031.0,Republican,Ted Cruz,45,0.600
24599,Wyoming,WY,Sweetwater-Carbon,95600026.0,Republican,Donald Trump,16,0.180
24600,Wyoming,WY,Sweetwater-Carbon,95600026.0,Republican,John Kasich,0,0.000
24601,Wyoming,WY,Sweetwater-Carbon,95600026.0,Republican,Marco Rubio,28,0.315
24602,Wyoming,WY,Sweetwater-Carbon,95600026.0,Republican,Ted Cruz,45,0.506
24603,Wyoming,WY,Teton-Sublette,95600028.0,Republican,Donald Trump,21,0.525
24604,Wyoming,WY,Teton-Sublette,95600028.0,Republican,John Kasich,0,0.000
24605,Wyoming,WY,Teton-Sublette,95600028.0,Republican,Marco Rubio,19,0.475
24606,Wyoming,WY,Teton-Sublette,95600028.0,Republican,Ted Cruz,0,0.000
24607,Wyoming,WY,Uinta-Lincoln,95600027.0,Republican,Donald Trump,0,0.000
24608,Wyoming,WY,Uinta-Lincoln,95600027.0,Republican,John Kasich,0,0.000
24609,Wyoming,WY,Uinta-Lincoln,95600027.0,Republican,Marco Rubio,0,0.000
24610,Wyoming,WY,Uinta-Lincoln,95600027.0,Republican,Ted Cruz,53,1.000

In [10]:
df_res['candidate'].value_counts()

Bernie Sanders     4205
Hillary Clinton    4205
Donald Trump       3586
John Kasich        3586
Ted Cruz           3586
Marco Rubio        2555
Ben Carson         1669
 No Preference      351
Jeb Bush            155
Chris Christie      109
Carly Fiorina       109
Rand Paul            99
 Uncommitted         99
Martin O'Malley      99
Mike Huckabee        99
Rick Santorum        99
Name: candidate, dtype: int64